### ISSUE TITLE
Weird Circles in Output

### ISSUE THREAD

**Issue by cybertech99** [Snapmaker/snapmaker_cnc_post_process#11]
Was doing a simple superman logo and doing the pocket and to validate used a cnc file viewer and saw these weird offshoot circles.

[Superman_fill.zip](https://github.com/Snapmaker/snapmaker_cnc_post_process/files/5393989/Superman_fill.zip)
![Capture](https://user-images.githubusercontent.com/16468130/96302992-aec53380-0fc7-11eb-8e21-22c05706d779.PNG)

**Comment by zjiefee** [comment]
This problem has been solved in https://github.com/Snapmaker/snapmaker_cnc_post_process/pull/9
