### ISSUE TITLE
Feature Request: Fusion 360 postprocessing for Artisan

### ISSUE THREAD

**Issue by tensile23** [Snapmaker/snapmaker_cnc_post_process#24]
- [x] Update the post-processor for Artisan
- [x] Adding new tool configurations to Artisan
- [ ] BUG fix: SM2.0 wrong use of RPM
- [ ] BUG fix: Rename B-axis Postprocessing

**Comment by matousrokos** [comment]
Hi, please don't forget that Fusion now supports adding whole machine profile not just post processor. That would come handy. Thanks
